[versions]
mod-version = "2.8.0"

# Fabric (https://fabricmc.net/develop)
jdk = "25"
minecraft = "26.2"
fabric-loader = "0.19.3"
fabric-api = "0.157.0+26.2"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.17-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "26.2-SNAPSHOT"

# Mods

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

# Mods

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
